Vagrant.configure("2") do |config|

    config.env.enable
    config.vm.box = ENV['vm_box']

    config.vm.define 'almalinux'

    config.vm.provider "libvirt" do |v|
        v.memory = 12288
        v.cpus = 4

        # The disk on 'mnt' pool for build results
        v.storage_pool_name = "mnt"
        v.storage :file, :size => '40G'
    end

    config.vm.provision "shell", inline: <<-SHELL
        # TODO: do not update for 10.x and Kitten images to avoid breaking 'vagrant scp':
        # kex_exchange_identification: read: Connection reset by peer
        [[ "#{ENV['vm_box']}" != *'10'* ]] && sudo dnf -y update || true
    SHELL

    # Reboot after update
    # TODO do not reboot 10.x and Kitten as they were not updated
    unless ENV['vm_box']&.include?('10')
        config.vm.provision :reload
    end
end
